/* Page-specific translations — menu, about, blog */
const pageTranslations = {
  en: {
    "nav.menu": "Menu",
    "nav.blog": "Blog",
    "footer.menu": "Our Menu",
    "footer.blog": "Blog & Cases",

    // Menu page
    "menu.breadcrumb": "Our Menu",
    "menu.eyebrow": "Culinary Showcase",
    "menu.title": "A Feast for the Eyes & Palate",
    "menu.lead": "From elegant canapés to contemporary mains and artisan desserts — explore our international menu crafted with premium local and imported ingredients.",
    "menu.cta": "Request Custom Menu",
    "menu.tab.all": "All",
    "menu.tab.canapes": "Canapés & Starters",
    "menu.tab.chinese": "Chef's Specials",
    "menu.tab.western": "Western Mains",
    "menu.tab.desserts": "Desserts",
    "menu.tab.beverages": "Beverages",
    "menu.note": "All menus are fully customisable. Dietary requirements including vegetarian, vegan, halal, and gluten-free options available upon request.",

    "menu.item1.tag": "Signature",
    "menu.item1.title": "Truffle Arancini",
    "menu.item1.desc": "Crispy risotto balls with black truffle, parmesan, and roasted garlic aioli.",
    "menu.item2.tag": "Starter",
    "menu.item2.title": "Beef Tartare Crostini",
    "menu.item2.desc": "Hand-cut wagyu tartare on toasted sourdough with capers and quail egg.",
    "menu.item3.tag": "Starter",
    "menu.item3.title": "Smoked Salmon Blinis",
    "menu.item3.desc": "Scottish smoked salmon on buckwheat blinis with crème fraîche and capers.",
    "menu.item4.tag": "Special",
    "menu.item4.title": "Seared Scallops",
    "menu.item4.desc": "Hokkaido scallops with pea purée, pancetta crisps, and lemon butter.",
    "menu.item5.tag": "Special",
    "menu.item5.title": "Herb-Crusted Lamb Rack",
    "menu.item5.desc": "Australian lamb with rosemary jus, fondant potato, and seasonal vegetables.",
    "menu.item6.tag": "Special",
    "menu.item6.title": "Lobster Risotto",
    "menu.item6.desc": "Creamy arborio rice with fresh lobster tail, saffron, and micro herbs.",
    "menu.item7.tag": "Main",
    "menu.item7.title": "Wagyu Beef Tenderloin",
    "menu.item7.desc": "Australian M9+ wagyu with truffle mash, seasonal vegetables, and red wine jus.",
    "menu.item8.tag": "Main",
    "menu.item8.title": "Pan-Seared Sea Bass",
    "menu.item8.desc": "Mediterranean sea bass with lemon beurre blanc and herb-roasted potatoes.",
    "menu.item9.tag": "Dessert",
    "menu.item9.title": "Chocolate Fondant",
    "menu.item9.desc": "Warm dark chocolate fondant with vanilla bean ice cream and berry coulis.",
    "menu.item10.tag": "Dessert",
    "menu.item10.title": "Tiramisu & Petit Fours",
    "menu.item10.desc": "Classic Italian tiramisu alongside French macarons and chocolate truffles.",
    "menu.item11.tag": "Dessert",
    "menu.item11.title": "Seasonal Fruit Platter",
    "menu.item11.desc": "Artfully arranged tropical and imported fruits with honey-lime drizzle.",
    "menu.item12.tag": "Beverage",
    "menu.item12.title": "Signature Gin & Tonic Bar",
    "menu.item12.desc": "Curated selection of premium gins with botanical garnishes and house-made tonics.",
    "menu.item13.tag": "Beverage",
    "menu.item13.title": "Champagne & Sparkling Selection",
    "menu.item13.desc": "Moët, Veuve Clicquot, and local sparkling wines for every celebration.",
    "menu.item14.tag": "Beverage",
    "menu.item14.title": "Craft Mocktail Programme",
    "menu.item14.desc": "Zero-proof cocktails with fresh herbs, seasonal fruits, and artisanal syrups.",

    // About page
    "aboutpage.breadcrumb": "About Us",
    "aboutpage.eyebrow": "Our Story",
    "aboutpage.title": "Passion for Food, Devotion to Service",
    "aboutpage.lead": "Founded in Hong Kong over 15 years ago, Lumina Catering was born from a simple belief — every event deserves extraordinary food and seamless hospitality.",
    "aboutpage.story.title": "Rooted in Hong Kong, Inspired by the World",
    "aboutpage.story.p1": "What started as a small team of passionate chefs serving intimate dinner parties in Mid-Levels has grown into one of Hong Kong's most trusted catering companies, serving over 500 events annually across the city.",
    "aboutpage.story.p2": "We draw inspiration from European, Mediterranean, and Asian flavours — creating menus that feel global yet personal to every host and occasion.",
    "aboutpage.team.eyebrow": "Meet the Team",
    "aboutpage.team.title": "The People Behind Every Plate",
    "aboutpage.team.lead": "Our diverse team of culinary professionals and event specialists bring decades of combined experience to every event.",
    "aboutpage.team1.name": "Chef Marcus Lee",
    "aboutpage.team1.role": "Executive Chef",
    "aboutpage.team1.desc": "20 years in Michelin-starred kitchens across Hong Kong and London. Specialises in East-West fusion cuisine.",
    "aboutpage.team2.name": "Grace Ho",
    "aboutpage.team2.role": "Event Director",
    "aboutpage.team2.desc": "Former luxury hotel events manager. Ensures every detail from setup to service exceeds expectations.",
    "aboutpage.team3.name": "Daniel Chan",
    "aboutpage.team3.role": "Head Sommelier",
    "aboutpage.team3.desc": "Certified sommelier with expertise in wine and cocktail pairings for multi-course banquets.",
    "aboutpage.team4.name": "Amy Wong",
    "aboutpage.team4.role": "Operations Manager",
    "aboutpage.team4.desc": "Logistics expert who coordinates kitchen, delivery, and on-site teams across all Hong Kong districts.",
    "aboutpage.values.eyebrow": "Our Values",
    "aboutpage.values.title": "What Drives Us",
    "aboutpage.value1.title": "Quality First",
    "aboutpage.value1.desc": "We source the freshest ingredients from trusted local markets and premium suppliers.",
    "aboutpage.value2.title": "Personal Touch",
    "aboutpage.value2.desc": "Every event receives a dedicated coordinator who knows your vision inside and out.",
    "aboutpage.value3.title": "Sustainability",
    "aboutpage.value3.desc": "Committed to reducing food waste and using eco-friendly packaging and serving ware.",

    // Blog page
    "blog.breadcrumb": "Blog & Cases",
    "blog.eyebrow": "Event Stories",
    "blog.title": "Experiences We've Created",
    "blog.lead": "Explore our recent events across Hong Kong — from rooftop weddings to corporate galas and intimate garden parties.",
    "blog.readmore": "Read Case Study",
    "blog.post1.tag": "Wedding",
    "blog.post1.title": "Rooftop Wedding at IFC with Harbour Views",
    "blog.post1.desc": "A 180-guest celebration featuring a contemporary European menu with live cooking stations and a champagne tower.",
    "blog.post1.date": "August 2026",
    "blog.post2.tag": "Corporate",
    "blog.post2.title": "Tech Giant Annual Gala at HKCEC",
    "blog.post2.desc": "500-person gala dinner with themed food stations, premium open bar, and coordinated multi-course service.",
    "blog.post2.date": "July 2026",
    "blog.post3.tag": "Private",
    "blog.post3.title": "Garden Party in Stanley",
    "blog.post3.desc": "An intimate 60-guest afternoon celebration with Mediterranean tapas, fresh seafood, and craft cocktails.",
    "blog.post3.date": "June 2026",
    "blog.post4.tag": "Corporate",
    "blog.post4.title": "Luxury Brand Product Launch",
    "blog.post4.desc": "Cocktail reception for 200 VIP guests in Central with bespoke canapés and signature drink pairings.",
    "blog.post4.date": "May 2026",
    "blog.post5.tag": "Corporate",
    "blog.post5.title": "Annual Awards Dinner at Rosewood",
    "blog.post5.desc": "Elegant three-course dinner for 250 guests with wine pairings and live jazz entertainment.",
    "blog.post5.date": "January 2026",
    "blog.post6.tag": "Charity",
    "blog.post6.title": "Charity Gala at The Peninsula",
    "blog.post6.desc": "Black-tie fundraising dinner with five-course French-Cantonese fusion menu and silent auction support.",
    "blog.post6.date": "November 2025",
  },

  zh: {
    "nav.menu": "菜單",
    "nav.blog": "博客",
    "footer.menu": "精選菜單",
    "footer.blog": "活動案例",

    "menu.breadcrumb": "精選菜單",
    "menu.eyebrow": "美食展示",
    "menu.title": "視覺與味覺的盛宴",
    "menu.lead": "從精緻小食到現代主菜及手工甜品——探索我們以優質本地及進口食材精心設計的國際菜單。",
    "menu.cta": "索取定制菜單",
    "menu.tab.all": "全部",
    "menu.tab.canapes": "小食及前菜",
    "menu.tab.chinese": "主廚推介",
    "menu.tab.western": "西式主菜",
    "menu.tab.desserts": "甜品",
    "menu.tab.beverages": "飲品",
    "menu.note": "所有菜單均可完全定制。素食、純素、清真及無麩質選項可按需提供。",

    "menu.item1.tag": "招牌",
    "menu.item1.title": "黑松露燉飯球",
    "menu.item1.desc": "酥脆燉飯球配黑松露、帕瑪森芝士及烤蒜蛋黃醬。",
    "menu.item2.tag": "前菜",
    "menu.item2.title": "和牛他他配脆包",
    "menu.item2.desc": "手切和牛他他配烤酸種麵包、酸豆及鵪鶉蛋。",
    "menu.item3.tag": "西式",
    "menu.item3.title": "煙三文魚薄餅",
    "menu.item3.desc": "蘇格蘭煙三文魚配蕎麥薄餅、酸忌廉及酸豆。",
    "menu.item4.tag": "推介",
    "menu.item4.title": "香煎帶子",
    "menu.item4.desc": "北海道帶子配豌豆蓉、意式培根脆片及檸檬牛油汁。",
    "menu.item5.tag": "推介",
    "menu.item5.title": "香草羊架",
    "menu.item5.desc": "澳洲羊架配迷迭香汁、薯餅及時令蔬菜。",
    "menu.item6.tag": "推介",
    "menu.item6.title": "龍蝦燴飯",
    "menu.item6.desc": "鮮龍蝦尾配奶油燴飯、藏紅花及微菜。",
    "menu.item7.tag": "西式",
    "menu.item7.title": "和牛菲力牛排",
    "menu.item7.desc": "澳洲M9+和牛配松露薯泥、時蔬及紅酒汁。",
    "menu.item8.tag": "西式",
    "menu.item8.title": "香煎海鱸魚",
    "menu.item8.desc": "地中海海鱸魚配檸檬奶油汁及香草烤薯。",
    "menu.item9.tag": "甜品",
    "menu.item9.title": "巧克力熔岩蛋糕",
    "menu.item9.desc": "溫熱黑巧克力熔岩蛋糕配雲呢拿雪糕及莓果醬。",
    "menu.item10.tag": "甜品",
    "menu.item10.title": "提拉米蘇及法式小點",
    "menu.item10.desc": "經典意式提拉米蘇配法式馬卡龍及巧克力松露。",
    "menu.item11.tag": "甜品",
    "menu.item11.title": "時令水果拼盤",
    "menu.item11.desc": "精心擺放的热帶及進口水果，配柚子蜜淋醬。",
    "menu.item12.tag": "飲品",
    "menu.item12.title": "招牌 Gin & Tonic 吧",
    "menu.item12.desc": "精選頂級氈酒配植物裝飾及自家調製湯力水。",
    "menu.item13.tag": "飲品",
    "menu.item13.title": "香檳及氣泡酒",
    "menu.item13.desc": "Moët、Veuve Clicquot 及本地氣泡酒，為每場慶典添彩。",
    "menu.item14.tag": "飲品",
    "menu.item14.title": "精品無酒精雞尾酒",
    "menu.item14.desc": "新鮮香草、時令水果及手工糖漿調製的零酒精雞尾酒。",

    "aboutpage.breadcrumb": "關於我們",
    "aboutpage.eyebrow": "我們的故事",
    "aboutpage.title": "對美食的熱忱，對服務的專注",
    "aboutpage.lead": "朗宴餐飲十五年前在香港創立，源於一個簡單的信念——每場活動都值得非凡的美食與無縫的款待。",
    "aboutpage.story.title": "扎根香港，放眼世界",
    "aboutpage.story.p1": "從半山小型晚宴起步，我們已發展為香港最受信賴的餐飲公司之一，每年服務超過500場活動。",
    "aboutpage.story.p2": "我們從歐洲、地中海及亞洲風味中汲取靈感，為每位主辦方打造既國際化又具個人特色的菜單。",
    "aboutpage.team.eyebrow": "認識團隊",
    "aboutpage.team.title": "每道菜背後的人",
    "aboutpage.team.lead": "我們多元化的烹飪專家及活動策劃團隊，為每場活動帶來數十年累積的經驗。",
    "aboutpage.team1.name": "李廚師 Marcus",
    "aboutpage.team1.role": "行政總廚",
    "aboutpage.team1.desc": "曾於香港及倫敦米其林餐廳工作20年，專精東西方融合料理。",
    "aboutpage.team2.name": "何小姐 Grace",
    "aboutpage.team2.role": "活動總監",
    "aboutpage.team2.desc": "前奢華酒店活動經理，確保從佈置到服務的每個細節都超越期望。",
    "aboutpage.team3.name": "陳先生 Daniel",
    "aboutpage.team3.role": "首席侍酒師",
    "aboutpage.team3.desc": "認證侍酒師，專精多道菜宴席的葡萄酒及雞尾酒搭配。",
    "aboutpage.team4.name": "黃小姐 Amy",
    "aboutpage.team4.role": "營運經理",
    "aboutpage.team4.desc": "物流專家，統籌廚房、運送及現場團隊，覆蓋香港各區。",
    "aboutpage.values.eyebrow": "我們的價值",
    "aboutpage.values.title": "驅動我們的力量",
    "aboutpage.value1.title": "品質至上",
    "aboutpage.value1.desc": "我們從可信賴的本地市場及優質供應商採購最新鮮食材。",
    "aboutpage.value2.title": "貼心服務",
    "aboutpage.value2.desc": "每場活動配備專屬統籌，深入了解您的每一個願景。",
    "aboutpage.value3.title": "可持續發展",
    "aboutpage.value3.desc": "致力減少食物浪費，使用環保包裝及餐具。",

    "blog.breadcrumb": "活動案例",
    "blog.eyebrow": "活動故事",
    "blog.title": "我們打造的體驗",
    "blog.lead": "探索我們近期在香港舉辦的活動——從天台婚禮到企業晚宴及私密花園派對。",
    "blog.readmore": "閱讀案例",
    "blog.post1.tag": "婚禮",
    "blog.post1.title": "國際金融中心天台婚禮",
    "blog.post1.desc": "180位賓客的慶典，當代歐式菜單，設現場烹飪站及香檳塔。",
    "blog.post1.date": "2026年8月",
    "blog.post2.tag": "企業",
    "blog.post2.title": "科技公司週年晚宴",
    "blog.post2.desc": "500人晚宴，主題美食站、高級開放吧及多道菜協調服務。",
    "blog.post2.date": "2026年7月",
    "blog.post3.tag": "私人",
    "blog.post3.title": "赤柱花園派對",
    "blog.post3.desc": "60位賓客的私密午後慶典，地中海小食、新鮮海鮮及精品雞尾酒。",
    "blog.post3.date": "2026年6月",
    "blog.post4.tag": "企業",
    "blog.post4.title": "奢侈品牌產品發佈會",
    "blog.post4.desc": "中環200位VIP賓客雞尾酒會，定制小食及招牌飲品搭配。",
    "blog.post4.date": "2026年5月",
    "blog.post5.tag": "企業",
    "blog.post5.title": "瑰麗酒店週年頒獎晚宴",
    "blog.post5.desc": "250位賓客的優雅三道菜晚宴，配葡萄酒搭配及現場爵士樂。",
    "blog.post5.date": "2026年1月",
    "blog.post6.tag": "慈善",
    "blog.post6.title": "半島酒店慈善晚宴",
    "blog.post6.desc": "黑色領帶籌款晚宴，五道菜法粵融合菜單及靜默拍賣支援。",
    "blog.post6.date": "2025年11月",
  },
};

Object.keys(pageTranslations.en).forEach((key) => {
  translations.en[key] = pageTranslations.en[key];
  translations.zh[key] = pageTranslations.zh[key];
});

if (typeof setLanguage === "function") setLanguage(currentLang);